import type { Metadata } from "next";
import "./globals.css";
import { Jost } from "next/font/google";


const jost = Jost({
  subsets: ["latin"],
  display: "swap",
});

const basePath = process.env.NEXT_PUBLIC_CUSTOM_IMAGE_BASE_PATH || '';
export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Next.js",
  icons:{
    icon : `${basePath}/Vv.png`
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jost.className}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
