import type { Metadata } from "next";
import "./globals.css";
import { Jost } from "next/font/google";




const jost = Jost({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jost.className}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
